import {
  AdminProject,
  AdminLead,
  AdminBlogPost,
  AdminAward,
  AdminTestimonial,
  AdminLeadership,
  CareerOpening,
  InvestorDoc,
  AdminNewsItem,
  AdminFaqItem,
  AdminCity,
  MasterAmenity,
  GlobalSettings,
  AdminUser,
  AdminPage,
  MediaAsset,
  AuditLog,
  NotificationItem,
} from './types';
import { PROJECTS } from '../../data/projects';
import { BLOG_POSTS } from '../../data/blog';
import { CITIES } from '../../data/cities';
import { VIDEO_TESTIMONIALS } from '../../data/testimonials';
import { LEADERSHIP } from '../../data/company';

export const SEED_USERS: AdminUser[] = [
  {
    id: 'usr-1',
    name: 'Prabhdeep Singh',
    email: 'prabhve5@gmail.com',
    role: 'Super Admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    status: 'active',
    twoFactorEnabled: true,
    lastLogin: '2026-09-16T18:45:00Z',
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2026-09-16T18:45:00Z',
  },
  {
    id: 'usr-2',
    name: 'Mohit Goel',
    email: 'mgoel@omaxe.com',
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    status: 'active',
    twoFactorEnabled: false,
    lastLogin: '2026-09-15T14:20:00Z',
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2026-09-15T14:20:00Z',
  },
  {
    id: 'usr-3',
    name: 'Aarti Sharma',
    email: 'aarti.s@omaxe.com',
    role: 'Sales Manager',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    status: 'active',
    twoFactorEnabled: false,
    lastLogin: '2026-09-16T12:10:00Z',
    createdAt: '2025-03-12T00:00:00Z',
    updatedAt: '2026-09-16T12:10:00Z',
  },
  {
    id: 'usr-4',
    name: 'Devendra Mehra',
    email: 'dmehra@omaxe.com',
    role: 'Content Editor',
    status: 'active',
    twoFactorEnabled: false,
    lastLogin: '2026-09-14T09:30:00Z',
    createdAt: '2025-04-05T00:00:00Z',
    updatedAt: '2026-09-14T09:30:00Z',
  },
];

export const SEED_MASTER_AMENITIES: MasterAmenity[] = [
  { id: 'am-1', name: 'Infinity Lap Pool', icon: 'Waves', category: 'Wellness', description: 'Olympic size temperature-controlled pool', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'am-2', name: 'Concierge & Valet', icon: 'Bell', category: 'Convenience', description: '24/7 dedicated resident lifestyle concierge', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'am-3', name: 'Biometric 7-Tier Security', icon: 'ShieldCheck', category: 'Security', description: 'Smart perimeter surveillance & boom barrier access', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'am-4', name: 'Private Screening Theatre', icon: 'Film', category: 'Recreation', description: 'Dolby Atmos 24-seater acoustically treated auditorium', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'am-5', name: 'Solar Microgrid & EV Stations', icon: 'Zap', category: 'Sustainability', description: '100% rooftop solar integration and fast EV charging', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'am-6', name: 'Sky Club & Cigar Lounge', icon: 'Wine', category: 'Recreation', description: 'High-altitude panorama clubhouse with private dining', createdAt: '2025-01-01T00:00:00Z' },
  { id: 'am-7', name: 'Helipad on Tower Pinnacle', icon: 'Plane', category: 'Convenience', description: 'Aviation certified emergency and VIP rooftop landing pad', createdAt: '2025-01-01T00:00:00Z' },
];

export const SEED_PROJECTS: AdminProject[] = PROJECTS.map((p: any, idx) => ({
  id: p.id || `proj-${idx + 1}`,
  name: p.title || p.name,
  slug: p.slug,
  category: (p.category as any) || 'residential',
  propertyTypes: p.type ? [p.type] : (p.propertyTypes || ['Luxury Apartments', 'Penthouses']),
  city: p.city,
  locality: p.location || p.city,
  fullAddress: `${p.location || 'Sector 82'}, ${p.city}, India`,
  lat: p.coordinates?.lat ?? (28.6139 + (idx * 0.05)),
  lng: p.coordinates?.lng ?? (77.209 + (idx * 0.04)),
  status: (p.status as any) || (idx === 0 ? 'Under Construction' : 'Ready to Move'),
  possessionDate: p.possession || p.possessionDate || 'Dec 2027',
  launchDate: 'Jan 2024',
  shortSummary: p.description ? p.description.slice(0, 180) : `Exclusive integrated development in ${p.city} by Omaxe Limited.`,
  descriptionHtml: `<p>${p.description || p.overview || 'Experience iconic architectural grandeur and sustainable township design.'}</p><p>Featuring private elevator lobbies, panoramic horizon decks, and world-class resort amenities.</p>`,
  startingPrice: p.priceStartingNumeric || (18500000 + idx * 2500000),
  pricePerSqFt: 14500,
  currency: 'INR',
  bookingAmount: 1000000,
  priceOnRequest: typeof p.priceStarting === 'string' ? p.priceStarting.toLowerCase().includes('request') : false,
  paymentPlans: [
    {
      id: 'plan-1',
      name: 'Construction Linked Milestone Plan (25:25:25:25)',
      description: 'Structured payment plan aligned with structural progress',
      milestones: [
        { id: 'm-1', milestone: 'Booking Amount & Allotment', percentage: 10, amountEstimate: '₹18,50,000' },
        { id: 'm-2', milestone: 'On Foundation Completion', percentage: 25, amountEstimate: '₹46,25,000' },
        { id: 'm-3', milestone: 'On Superstructure Cast', percentage: 40, amountEstimate: '₹74,00,000' },
        { id: 'm-4', milestone: 'On Notice of Possession', percentage: 25, amountEstimate: '₹46,25,000' },
      ],
    },
  ],
  configurations: [
    {
      id: `cfg-${idx}-1`,
      name: '3 BHK Grande Suite',
      carpetArea: 1850,
      builtUpArea: 2250,
      superArea: 2650,
      unit: 'sq.ft.',
      priceFrom: 18500000,
      priceTo: 22000000,
      priceOnRequest: false,
      availabilityCount: 8,
      floorPlanImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      isProtected: false,
    },
    {
      id: `cfg-${idx}-2`,
      name: '4 BHK Presidential Sky Villa',
      carpetArea: 2900,
      builtUpArea: 3500,
      superArea: 4200,
      unit: 'sq.ft.',
      priceFrom: 32000000,
      priceTo: 38000000,
      priceOnRequest: false,
      availabilityCount: 3,
      floorPlanImage: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      isProtected: true,
    },
  ],
  highlights: [
    { id: 'h-1', icon: 'Compass', title: 'Triple Height Private Elevator Foyer', description: 'Dedicated direct lift access into your personal entrance gallery.' },
    { id: 'h-2', icon: 'Sparkles', title: 'Curated Italian Marble & Teak Finishes', description: 'Imported Botticino marble flooring and double-glazed acoustical glass.' },
    { id: 'h-3', icon: 'Shield', title: 'IGBC Platinum Certified Green Habitat', description: 'Zero-discharge rainwater harvesting and 85% open landscaped parklands.' },
  ],
  amenities: [
    { amenityId: 'am-1', isFeatured: true },
    { amenityId: 'am-2', isFeatured: true },
    { amenityId: 'am-3', isFeatured: false },
    { amenityId: 'am-4', isFeatured: true },
    { amenityId: 'am-5', isFeatured: false },
  ],
  gallery: [
    {
      id: `img-${idx}-1`,
      url: p.image || 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80',
      caption: 'Architectural facade during twilight',
      altText: `${p.title || p.name || 'Omaxe'} luxury exterior architecture`,
      category: 'Exterior',
      isCover: true,
      isHero: true,
      order: 0,
    },
    {
      id: `img-${idx}-2`,
      url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
      caption: 'Double height living hall',
      altText: 'Interior living space with panoramic windows',
      category: 'Interior',
      isCover: false,
      isHero: false,
      order: 1,
    },
    {
      id: `img-${idx}-3`,
      url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
      caption: 'Infinity pool and clubhouse deck',
      altText: 'Clubhouse deck overlooking landscaped greens',
      category: 'Amenities',
      isCover: false,
      isHero: false,
      order: 2,
    },
  ],
  videos: [
    {
      id: `vid-${idx}-1`,
      type: 'youtube',
      url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      title: 'Architectural Walkthrough & Aerial Cinema',
      posterUrl: p.image,
      tag: 'Walkthrough',
    },
  ],
  locationAdvantages: [
    { id: 'loc-1', landmarkName: 'International Airport Hub', category: 'Airport', distanceValue: 18, distanceUnit: 'km', travelTime: '22 mins drive' },
    { id: 'loc-2', landmarkName: 'Metro Express Station', category: 'Metro', distanceValue: 1.2, distanceUnit: 'km', travelTime: '3 mins walk' },
    { id: 'loc-3', landmarkName: 'World Class Multi-Speciality Hospital', category: 'Hospital', distanceValue: 3.5, distanceUnit: 'km', travelTime: '8 mins drive' },
  ],
  specifications: [
    { id: 'sp-1', roomType: 'Living & Dining', flooring: 'Imported Botticino Italian Marble', walls: 'Acrylic Emulsion Paint with POP Punning', fittings: 'Concealed LED cove lighting' },
    { id: 'sp-2', roomType: 'Master Suite', flooring: 'Engineered Hardwood Teak', walls: 'Velvet Matte Finish with acoustic backing', fittings: 'Walk-in dressing suite with Italian cabinetry' },
    { id: 'sp-3', roomType: 'Modular Kitchen', flooring: 'Anti-skid Italian Quartz Tile', walls: 'Ceramic backsplash with quartz countertop', fittings: 'Miele/Siemens chimney, hob, microwave and dishwasher' },
  ],
  documents: [
    { id: `doc-${idx}-1`, title: 'Executive Project Brochure & Floor Book', type: 'Brochure', fileUrl: '/documents/brochure-sample.pdf', fileSize: '14.8 MB', accessLevel: 'requires_lead' },
    { id: `doc-${idx}-2`, title: 'State RERA Registration Certificate', type: 'RERA Certificate', fileUrl: '/documents/rera-sample.pdf', fileSize: '1.2 MB', accessLevel: 'public' },
    { id: `doc-${idx}-3`, title: 'Ministry Environmental Clearance Order', type: 'EC Clearance', fileUrl: '/documents/ec-sample.pdf', fileSize: '3.4 MB', accessLevel: 'public' },
  ],
  reraNumber: p.reraNo || p.reraNumber || `UPRERA/PRJ/${2024 + idx}/8910`,
  reraAuthority: 'State Real Estate Regulatory Authority',
  reraQrCode: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=300&q=80',
  approvalAuthority: 'Directorate of Town and Country Planning (DTCP)',
  totalLandArea: '25.5 Acres',
  numberOfTowers: 6,
  numberOfFloors: 38,
  numberOfUnits: 420,
  openAreaPercent: 82,
  legalDisclaimer: 'Approvals granted by DTCP vide Memo No. 8921. RERA registration verified and active.',
  publishedState: 'published',
  isFeatured: idx < 5,
  isHero: idx === 0,
  displayOrder: idx,
  showEnquiryForm: true,
  customCtaLabel: 'Schedule Private Viewing',
  customCtaLink: '#enquire',
  seo: {
    metaTitle: `${p.title || p.name} | Luxury Properties in ${p.city} | Omaxe Limited`,
    metaDescription: `Explore ${p.title || p.name} in ${p.city}. Ultra-luxury residences and penthouses with world-class clubhouse, 7-tier security, and scenic skyline views.`,
    keywords: [p.title || p.name || 'Omaxe', p.city, 'Luxury Apartments', 'Omaxe Properties', 'RERA Approved'],
    noIndex: false,
  },
  viewsCount: 14200 + (idx * 850),
  enquiriesCount: 148 + (idx * 19),
  revisions: [],
  createdAt: '2025-01-15T00:00:00Z',
  updatedAt: '2026-09-14T10:00:00Z',
}));

export const SEED_LEADS: AdminLead[] = [
  {
    id: 'lead-1',
    name: 'Vikramaditya Oberoi',
    email: 'v.oberoi@theoberoigroup.com',
    phone: '+91 98110 44219',
    city: 'New Delhi',
    projectName: 'The Lake Luxury Towers',
    residentType: 'Indian Resident',
    budgetBand: '₹5 Cr – ₹10 Cr',
    message: 'Seeking a duplex penthouse on high floor with terrace plunge pool and 4 covered parking slots.',
    sourcePage: '/projects/the-lake-luxury-towers',
    utmSource: 'google_cpc',
    utmMedium: 'luxury_search',
    utmCampaign: 'delhi_ncr_q3',
    device: 'Desktop',
    ipLocation: 'New Delhi, India',
    status: 'Site Visit Scheduled',
    assignedToUser: 'Aarti Sharma',
    assignedUserEmail: 'aarti.s@omaxe.com',
    scheduledFollowUpAt: '2026-09-18T11:00:00Z',
    notes: [
      {
        id: 'n-1',
        authorName: 'Aarti Sharma',
        text: 'Client is an industrialist looking for immediate self-use. Site visit confirmed for Friday morning with chauffeur service.',
        mentions: ['Mohit Goel'],
        createdAt: '2026-09-16T10:15:00Z',
      },
    ],
    activityLog: [
      { id: 'act-1', type: 'status_change', description: 'Status changed from New to Site Visit Scheduled', actorName: 'Aarti Sharma', timestamp: '2026-09-16T10:16:00Z' },
    ],
    isDuplicate: false,
    createdAt: '2026-09-16T08:30:00Z',
    updatedAt: '2026-09-16T10:16:00Z',
  },
  {
    id: 'lead-2',
    name: 'Dr. Sunita Deshmukh',
    email: 'dr.sunita@aiims.edu',
    phone: '+91 99201 88344',
    city: 'Lucknow',
    projectName: 'Grand Omaxe Heritage',
    residentType: 'Indian Resident',
    budgetBand: '₹2.5 Cr – ₹5 Cr',
    message: 'Interested in 4 BHK park-facing unit for elderly parents.',
    sourcePage: '/properties-in/lucknow',
    device: 'Mobile',
    status: 'Qualified',
    assignedToUser: 'Aarti Sharma',
    notes: [],
    activityLog: [],
    isDuplicate: false,
    createdAt: '2026-09-16T06:12:00Z',
    updatedAt: '2026-09-16T07:00:00Z',
  },
  {
    id: 'lead-3',
    name: 'Rajesh Mehta (NRI)',
    email: 'rmehta@dubaiinvest.ae',
    phone: '+971 50 892 1092',
    city: 'Chandigarh',
    projectName: 'Omaxe Heights Iconic',
    residentType: 'Non-Resident Indian (NRI)',
    budgetBand: '₹3 Cr – ₹6 Cr',
    message: 'Looking to invest in commercial retail frontage or luxury residence.',
    sourcePage: '/projects',
    device: 'Tablet',
    status: 'New',
    notes: [],
    activityLog: [],
    isDuplicate: false,
    createdAt: '2026-09-16T05:00:00Z',
    updatedAt: '2026-09-16T05:00:00Z',
  },
  {
    id: 'lead-4',
    name: 'Ananya Singhania',
    email: 'ananya@singhaniatrading.in',
    phone: '+91 98450 11992',
    city: 'Faridabad',
    projectName: 'Omaxe Royal Residency',
    residentType: 'Corporate / Institutional',
    budgetBand: '₹10 Cr+',
    message: 'Corporate guesthouse requirement - 6 adjoining units.',
    sourcePage: '/contact',
    device: 'Desktop',
    status: 'Negotiation',
    assignedToUser: 'Mohit Goel',
    notes: [],
    activityLog: [],
    isDuplicate: false,
    createdAt: '2026-09-15T16:40:00Z',
    updatedAt: '2026-09-16T09:00:00Z',
  },
];

export const SEED_MEDIA: MediaAsset[] = [
  {
    id: 'med-1',
    fileName: 'omaxe-lake-exterior-twilight.jpg',
    title: 'The Lake Luxury Towers Facade',
    altText: 'The Lake luxury towers illuminated exterior against twilight sky',
    url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80',
    mimeType: 'image/jpeg',
    sizeBytes: 2450000,
    width: 2560,
    height: 1440,
    folderPath: '/Projects/The-Lake',
    tags: ['exterior', 'twilight', 'residential', 'hero'],
    usedIn: [{ entityType: 'project', entityId: 'proj-1', title: 'The Lake Luxury Towers' }],
    variants: [],
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2025-01-10T00:00:00Z',
  },
  {
    id: 'med-2',
    fileName: 'omaxe-interior-grand-salon.jpg',
    title: 'Grand Salon Living Room',
    altText: 'Spacious double-height luxury salon with imported marble',
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
    mimeType: 'image/jpeg',
    sizeBytes: 1890000,
    width: 1920,
    height: 1080,
    folderPath: '/Projects/Interiors',
    tags: ['interior', 'living-room', 'marble'],
    usedIn: [{ entityType: 'project', entityId: 'proj-1', title: 'The Lake Luxury Towers' }],
    variants: [],
    createdAt: '2025-01-12T00:00:00Z',
    updatedAt: '2025-01-12T00:00:00Z',
  },
  {
    id: 'med-3',
    fileName: 'omaxe-infinity-pool-deck.jpg',
    title: 'Infinity Sky Pool',
    altText: 'Rooftop infinity swimming pool with lounge cabanas',
    url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80',
    mimeType: 'image/jpeg',
    sizeBytes: 3100000,
    width: 2400,
    height: 1600,
    folderPath: '/Amenities',
    tags: ['amenities', 'pool', 'wellness'],
    usedIn: [{ entityType: 'project', entityId: 'proj-2', title: 'Grand Omaxe Heritage' }],
    variants: [],
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2025-01-15T00:00:00Z',
  },
];

export const SEED_BLOG_POSTS: AdminBlogPost[] = BLOG_POSTS.map((b: any, idx) => ({
  id: b.id || `blog-${idx + 1}`,
  title: b.title,
  slug: b.slug,
  excerpt: b.excerpt,
  content: b.content,
  coverImage: b.image || b.coverImage || 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
  category: b.category,
  tags: b.tags || ['Market Analysis', 'Real Estate', 'Omaxe Insights'],
  author: b.author || 'Omaxe Editorial Desk',
  readTime: b.readTime || '6 min read',
  featured: idx === 0,
  status: 'published',
  publishedDate: b.date || '2026-08-15',
  seo: {
    metaTitle: `${b.title} | The Omaxe Journal`,
    metaDescription: b.excerpt ? b.excerpt.slice(0, 155) : '',
    keywords: b.tags || ['Omaxe', 'Real Estate'],
    noIndex: false,
  },
  createdAt: '2025-06-01T00:00:00Z',
  updatedAt: '2026-08-15T00:00:00Z',
}));

export const SEED_AWARDS: AdminAward[] = [
  { id: 'aw-1', title: 'Developer of the Year - Ultra Luxury Residential', organization: 'National Real Estate Leadership Awards', year: 2026, category: 'Residential Excellence', linkedProject: 'The Lake Luxury Towers', isFeatured: true, order: 0, createdAt: '2026-01-10T00:00:00Z' },
  { id: 'aw-2', title: 'Best Integrated Township Developer (Pan-India)', organization: 'CNBC-Awaaz Real Estate Conclave', year: 2025, category: 'Township Masterplanning', isFeatured: true, order: 1, createdAt: '2025-11-20T00:00:00Z' },
  { id: 'aw-3', title: 'Excellence in Sustainable & Green Building Design', organization: 'IGBC Green Habitat Summit', year: 2025, category: 'Sustainability', isFeatured: true, order: 2, createdAt: '2025-09-05T00:00:00Z' },
];

export const SEED_TESTIMONIALS: AdminTestimonial[] = VIDEO_TESTIMONIALS.map((t: any, idx) => ({
  id: t.id || `test-${idx + 1}`,
  clientName: t.name,
  designationOrProject: t.descriptor || t.project || 'Esteemed Resident',
  city: 'Delhi NCR',
  quoteText: t.quote,
  videoUrl: t.youtubeUrl,
  photoUrl: t.avatar,
  rating: 5,
  isFeatured: idx < 3,
  status: 'approved',
  createdAt: '2025-05-10T00:00:00Z',
}));

export const SEED_LEADERSHIP: AdminLeadership[] = LEADERSHIP.map((l: any, idx) => ({
  id: `lead-exec-${idx + 1}`,
  name: l.name,
  designation: l.role || l.designation || l.title || 'Executive Leader',
  shortBio: l.bio,
  longBio: `${l.bio} Spearheading transformative real estate developments across 31 cities with commitment to governance and structural excellence.`,
  photoUrl: l.image,
  linkedinUrl: 'https://linkedin.com/company/omaxe-limited',
  displayOrder: idx,
  createdAt: '2025-01-01T00:00:00Z',
}));

export const SEED_CITIES: AdminCity[] = CITIES.map((c: any, idx) => ({
  id: String(c.id || idx + 1),
  name: c.name,
  slug: c.slug,
  state: c.state,
  heroImage: c.image || 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1600&q=80',
  introCopy: c.description || `Explore premier residential estates and integrated townships by Omaxe in ${c.name}.`,
  displayOrder: idx,
  isActive: true,
  seo: {
    metaTitle: `Properties in ${c.name} | Omaxe Limited`,
    metaDescription: `Discover luxury residential and commercial properties in ${c.name}, ${c.state}.`,
    keywords: [c.name, c.state, 'Real Estate', 'Townships'],
    noIndex: false,
  },
  createdAt: '2025-01-01T00:00:00Z',
}));

export const SEED_GLOBAL_SETTINGS: GlobalSettings = {
  brand: {
    siteName: 'Omaxe Limited',
    tagline: 'Turning Dreams into Reality',
    logoLight: '/images/omaxe-logo-white.svg',
    logoDark: '/images/omaxe-logo-dark.svg',
    favicon: '/favicon.ico',
    ogDefaultImage: '/images/hero-home.jpg',
    primaryGoldColor: '#A8823C',
    primaryInkColor: '#131616',
  },
  contact: {
    headquartersAddress: 'Omaxe City Centre, Sector 11, Faridabad, Haryana 121006',
    registeredOffice: 'Omaxe House, 7 Local Shopping Centre, Kalkaji, New Delhi 110019',
    tollFreeNumber: '1800-102-0064',
    salesNumber: '+91-11-41893100',
    whatsappNumber: '+91-99999-06293',
    generalEmail: 'info@omaxe.com',
    salesEmail: 'sales@omaxe.com',
    investorEmail: 'investors@omaxe.com',
  },
  social: {
    facebook: { url: 'https://facebook.com/OmaxeLimited', isVisible: true },
    instagram: { url: 'https://instagram.com/omaxelimited', isVisible: true },
    linkedin: { url: 'https://linkedin.com/company/omaxe-limited', isVisible: true },
    youtube: { url: 'https://youtube.com/user/omaxelimited', isVisible: true },
    x: { url: 'https://twitter.com/OmaxeLimited', isVisible: true },
  },
  footer: {
    disclaimerText: 'Disclaimer: The information provided on this website is for informational purposes only and does not constitute an offer, guarantee, or legal advice. All visual representations, renders, and amenities are artist impressions. Project specifications are subject to approvals.',
    copyrightText: '© 1987–2026 Omaxe Limited. All Rights Reserved. CIN: L74899DL1989PLC038050',
    newsletterHeading: 'Subscribe to The Omaxe Journal',
    consentCopy: 'I consent to receive privileged investor updates and portfolio invitations from Omaxe Limited.',
  },
  bannersAndPopups: [],
  forms: {
    enquiryFields: {
      requireCity: true,
      requireProject: false,
      requireBudget: false,
      requireResidentType: true,
      consentNoticeText: 'I authorize Omaxe Limited to contact me via phone, email, and WhatsApp.',
      successMessage: 'Thank you for connecting. An Omaxe Relationship Partner will contact you shortly.',
      notificationRecipients: ['leads@omaxe.com', 'sales@omaxe.com'],
    },
  },
  integrations: {
    gtmId: 'GTM-WB4F8MS',
    ga4Id: 'G-XXXXXXXXXX',
    googleMapsApiKey: '',
    recaptchaSiteKey: '',
  },
  maintenance: {
    isEnabled: false,
    message: 'Our digital experience is undergoing scheduled maintenance. Please check back shortly or contact our 24/7 concierge at 1800-102-0064.',
    allowedIps: [],
  },
};

export const SEED_PAGES: AdminPage[] = [
  {
    id: 'page-home',
    title: 'Home — Omaxe Luxury Portfolio',
    slug: '',
    template: 'home',
    blocks: [
      { id: 'b-1', type: 'HeroSlider', name: 'Hero Carousel', isHidden: false, settings: {}, styles: { background: 'ink', paddingTop: 'none', paddingBottom: 'none', containerWidth: 'full', textAlign: 'left' } },
      { id: 'b-2', type: 'SplitIntro', name: 'Corporate Philosophy Intro', isHidden: false, settings: {}, styles: { background: 'ivory', paddingTop: 'lg', paddingBottom: 'lg', containerWidth: 'normal', textAlign: 'left' } },
      { id: 'b-3', type: 'StatsBand', name: 'Legacy Numbers Band', isHidden: false, settings: {}, styles: { background: 'cream', paddingTop: 'md', paddingBottom: 'md', containerWidth: 'normal', textAlign: 'left' } },
      { id: 'b-4', type: 'WhyChooseOmaxe', name: 'Why Choose Omaxe Pillars', isHidden: false, settings: {}, styles: { background: 'ivory', paddingTop: 'lg', paddingBottom: 'lg', containerWidth: 'normal', textAlign: 'left' } },
      { id: 'b-5', type: 'ProjectGrid', name: 'Signature Developments', isHidden: false, settings: {}, styles: { background: 'cream', paddingTop: 'xl', paddingBottom: 'xl', containerWidth: 'normal', textAlign: 'left' } },
      { id: 'b-6', type: 'PresenceMap', name: 'Pan-India 31 Cities Presence', isHidden: false, settings: {}, styles: { background: 'ivory', paddingTop: 'lg', paddingBottom: 'lg', containerWidth: 'normal', textAlign: 'left' } },
      { id: 'b-7', type: 'LeadershipGrid', name: 'Founding Leadership', isHidden: false, settings: {}, styles: { background: 'cream', paddingTop: 'lg', paddingBottom: 'lg', containerWidth: 'normal', textAlign: 'left' } },
      { id: 'b-8', type: 'TestimonialSlider', name: 'Resident Video Testimonials', isHidden: false, settings: {}, styles: { background: 'ivory', paddingTop: 'lg', paddingBottom: 'lg', containerWidth: 'normal', textAlign: 'left' } },
      { id: 'b-9', type: 'AwardsMarquee', name: 'Accolades Marquee', isHidden: false, settings: {}, styles: { background: 'cream', paddingTop: 'md', paddingBottom: 'md', containerWidth: 'full', textAlign: 'left' } },
      { id: 'b-10', type: 'InTheNewsStrip', name: 'In The News Strip', isHidden: false, settings: {}, styles: { background: 'ivory', paddingTop: 'md', paddingBottom: 'md', containerWidth: 'normal', textAlign: 'left' } },
      { id: 'b-11', type: 'JournalRow', name: 'Editorial Journal', isHidden: false, settings: {}, styles: { background: 'cream', paddingTop: 'lg', paddingBottom: 'lg', containerWidth: 'normal', textAlign: 'left' } },
      { id: 'b-12', type: 'CtaBand', name: 'Concierge Consultation CTA', isHidden: false, settings: {}, styles: { background: 'ink', paddingTop: 'lg', paddingBottom: 'lg', containerWidth: 'full', textAlign: 'center' } },
    ],
    status: 'published',
    includeInNavigation: true,
    navigationLabel: 'Home',
    authorName: 'Prabhdeep Singh',
    seo: {
      metaTitle: 'Omaxe Limited | India’s Premier Real Estate Developer',
      metaDescription: 'Pioneering luxury integrated townships, sports cities, commercial hubs, and premium residences.',
      keywords: ['Omaxe', 'Townships', 'Real Estate'],
      noIndex: false,
    },
    revisions: [],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-09-16T18:00:00Z',
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    userId: 'usr-1',
    userName: 'Prabhdeep Singh',
    userEmail: 'prabhve5@gmail.com',
    actorName: 'Prabhdeep Singh',
    actorEmail: 'prabhve5@gmail.com',
    module: 'Projects',
    targetTitle: 'The Lake Luxury Towers',
    entityType: 'project',
    entityId: 'proj-1',
    action: 'update',
    ipAddress: '103.21.144.12',
    summary: 'Updated pricing and configuration floorplans for The Lake Luxury Towers',
    timestamp: '2026-09-16T18:40:00Z',
  },
  {
    id: 'aud-2',
    userId: 'usr-3',
    userName: 'Aarti Sharma',
    userEmail: 'aarti.s@omaxe.com',
    actorName: 'Aarti Sharma',
    actorEmail: 'aarti.s@omaxe.com',
    module: 'Leads CRM',
    targetTitle: 'Vikramaditya Oberoi (Lead)',
    entityType: 'lead',
    entityId: 'lead-1',
    action: 'update',
    ipAddress: '14.139.221.10',
    summary: 'Scheduled site visit for lead Vikramaditya Oberoi',
    timestamp: '2026-09-16T10:16:00Z',
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'High-Value VIP Lead Received',
    message: 'Vikramaditya Oberoi enquired for The Lake Luxury Towers (₹5 Cr – ₹10 Cr).',
    type: 'lead',
    link: '/admin/leads/lead-1',
    isRead: false,
    createdAt: '2026-09-16T08:30:00Z',
  },
  {
    id: 'notif-2',
    title: 'New Review Request',
    message: 'Devendra Mehra submitted "Q3 2026 Housing Trends" blog post for approval.',
    type: 'review_request',
    link: '/admin/blog',
    isRead: false,
    createdAt: '2026-09-16T04:15:00Z',
  },
  {
    id: 'notif-3',
    title: 'System Security Audit Clean',
    message: 'Automated vulnerability and RERA clearance scan completed with 0 errors.',
    type: 'system',
    isRead: true,
    createdAt: '2026-09-15T22:00:00Z',
  },
];
